remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Camille Sze Pui Ko
logo: "images/b1f8ed8e-9927-467a-82df-38a887d0cb75.JPG" # your photo (or logo) here
description: >
  
  <a href=" https://sacommunity.org/node/1081">Volunteer Data Analyst @ Infoxchange </a> 
  | PT Lecturer @ School of Computer Science, The University of Adelaide
  
  <br><br>
  <img src="https://skillicons.dev/icons?i=aws,gcp,azure,py,pytorch,tensorflow,mysql,r,java,git,firebase,docker,django,html,css,c,cs,cpp,bash,anaconda&perline=10" alt="My Skills">
  <br><br>
  <img src="images/aws-cp.png" alt="Certified AWS Cloud Practitioner (CLF-C01)" width="20" height="20">
  <img src="images/azure-dp100.png" alt="Certified Microsoft Azure Data Fundamentals (DP-100)" width="20" height="20">
  <img src="images/azure-ai900.png" alt="Certified Microsoft Azure AI Fundamentals (AI-900)" width="20" height="20">
  <img src="images/tableau-ds.png" alt="Certified Tableau Scientist" width="20" height="20">
  <img src="images/tableau-da.png" alt="Certified Tableau Analyst" width="20" height="20">

  <a href="https://www.linkedin.com/in/camilleko/">View My LinkedIn Profile</a> 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
