remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Camille Sze Pui Ko
logo: "/images/camillekokoko.JPG?raw=true" # your photo (or logo) here
description: >
  
  <a href=" https://sacommunity.org/node/1081">Volunteer Data Analyst @ Infoxchange </a> 
  | PT Lecturer @ School of Computer Science, The University of Adelaide
  
  <br><br>
  <img src="https://skillicons.dev/icons?i=aws,gcp,azure,py,pytorch,tensorflow,mysql,r,java,git,firebase,docker,django,html,css,c,cs,cpp,bash,anaconda&perline=10" alt="My Skills">
  <br><br>
  <a href="https://www.linkedin.com/in/camilleko/">View My LinkedIn Profile</a> 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
